services:
  - type: web
    name: vehicle-failure-prediction
    runtime: python
    pythonVersion: 3.12
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"

